### ISSUE TITLE
summing displacement over too long of a range `flag_idmc_global_yearly`

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/pa-global-monitoring#11]
`cs_temp_` var is creating just 1 group for the entire time range (DRC & `flag_idmc_global_yearly`).

Issue is occurring in this line, but it could be due to something in this script or possibly `{idmc}` package or API.

https://github.com/OCHA-DAP/pa-global-monitoring/blob/6858c7004f57049abc7f4bebad72758573759fb9/src/indicators/idmc/run.R#L79

Will post back when I figure out. If error originates from this repo or can be patched here , I will make a new branch and flag here.

**Comment by zackarno** [comment]
just flagging that the issue is on hold for the time being as it is non-urgent and somewhat by design. However, we should eventually address

**Comment by zackarno** [comment]
The issue arises from the way the script sums across dates. Displacement figures from consecutively “flagged” dates are summed. DRC has been flagged every day since 2018 from the yearly rolling sum check/flag – this is why it sums across all those dates and produces such a high value.

I think this is largely by design, but perhaps the wording and flagging needs some re-thinking w/ respect to the time range being flagged. One possible solution for the yearly rolling sum flag could be to just sum the displacement over the previous year and mention that it’s been anomalous for longer, something like: “XX displacements occurred between 20 January 2022 and 20 January 2023. Since January 2018 DRC has experienced anomalously high displacement with an average of YY displacements/year.”

**Comment by caldwellst** [comment]
Just opened up this issue, and had the exact same thought on the solution! I think only reporting up to 1 year back makes the most sense. And I hadn't thought about the reporting of things previously, like back to January 2018. Really nice. Will work on a PR that fits this solution.

**Comment by caldwellst** [comment]
I have addressed this in the new branch where I completely reconfigure how we might aggregate up single vector based flags based on time anomalies. It got me thinking that actually in the email alerts, we don't need to contextualise over such a long period, but just across the period that led to the alert. The rest of the information should be self contained within the plot to a degree where they can see trends over the past # of years.

Will close when pushed.
