### ISSUE TITLE
global-monitoring GH Action failure (`{renv}` + caching = problem)

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/pa-global-monitoring#12]
Several failures in CRON scheduled GH actions (50-74). The issue appears to arise due to the interaction of package caching the `{renv}` package. 
 
Issue can be manually fixed by deleting cache  in GitHub and manually running workflow again. After deleting cache CRON job will run successfully several times until failing, at which point the above can be repeated.

Rather than having to continually check and delete cache on the GitHub repo, I think an easy fix is just to delete the caching step of the action. I’d rather have a 10 minute fully automated run the having to check and manually trigger for a faster 2 minute run.

I removed the caching step in a branch with 713bc0f and had a successful manual run (#75). I will do a PR, merge, and monitor the CRON jobs over the coming week
 
Will post some leads on the `{renv}` + caching issue to hopefully troubleshoot and integrate caching back in eventually

**Comment by zackarno** [comment]
temporarily increased CRON freq to make sure removal of caching step will serve as stop-gap for the next couple weeks 30e2ab4ae9e0a8fd21df4ae62dbd5bc500089407

If no issues in GH action runs, will change freq back to just M-F at 11 am

**Comment by zackarno** [comment]
[run # 78 ](https://github.com/OCHA-DAP/pa-global-monitoring/actions/runs/5369405490) failed even though caching step was removed. Therefore, the issue appears not directly related the GHA caching step, rather just `renv::restore()` and `{ripc}`. I re-ran #78 again and it failed. I then deleted the cache and ran as a new workflow and it succeeded. Don't know if deleting the cache or running as new workflow was the key to success in this case as the caching step would seem unrelated now.

I've noticed a pattern of 3 successful runs -> failure.

I am going to add the caching action back in and reset to normal schedule soon.

**Comment by zackarno** [comment]
Some failed runs - issue still not resolved so I reverted yaml back to how it was:
- Since caching action was not the issue, I added the step back in e847339918a25cbe3fe6966a481d5f9b86894804
- switched CRON job back to intended schedule 6b16ed92b950629d43d274a3b2b9f613663f503c

By manually re-running it seems to eventually work successfully

**Comment by caldwellst** [comment]
The issue with the global monitoring seemed to stem from `rhdx` and `sf` at different points in time running on MacOS. In particular, you have to worry about installing from source or binary for `sf`. Not sure what the issue with `rhdx` was. I have finally gotten the system to re-run running on `ubuntu-latest` and I removed the already deprecated functions from `Ripc` that relied on `rhdx`, so we no longer need to use the package.

Will re-open if we run into issues again, but hopefully this has solved everything!
