### ISSUE TITLE
GHA failed runs (potential cross repo issue)

### ISSUE THREAD

**Issue by zackarno** [OCHA-DAP/pa-global-monitoring#32]
I noticed some GHA issues in the last day or 2 for YEM & NGA so i checked here and looks like some new issues. I wonder if they could be related to the google apis we are using. Have not dug into them at all yet, but posting it here so we can remember to chat about it quickly next week

**Comment by zackarno** [comment]
okay NGA GHA failure completely unrelated (not sure on YEM yet)

https://github.com/OCHA-DAP/ds-nga-flood-monitoring/issues/10#issue-1898625968

**Comment by caldwellst** [comment]
Here also unrelated, was an error in the recursive code I put for AI summarisation which I just fixed. Thanks for noticing though! I'm away this week but back next to chat about it. Will be monitoring global monitoring though just to ensure it runs.
